application:
  kafka-topics:
    purchase-requests: flashsale.purchase.requests
    flashsale-events: flashsale.events

spring:
  application.name: flashsale-events-api
  cloud:
    gcp:
      project-id: flashsale-456707
      secretmanager:
        enabled: false
      core:
        enabled: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
      acks: all
    consumer:
      group-id: flashsale-events-api-consumer-group